server:
  port: ${services.ports.notification}
spring:
  application:
    name: notification

  datasource:
    url: jdbc:postgresql://localhost:5432/assigno
    username: postgres
    password: root123

  jpa:
    properties:
      hibernate:
        default_schema: notifications

    hibernate:
      ddl-auto: update

    show-sql: true
