server:
  port: ${services.ports.task}
spring:
  application:
    name: task

  datasource:
    url: jdbc:postgresql://localhost:5432/assigno
    username: postgres
    password: root123

  jpa:
    properties:
      hibernate:
        default_schema: task

    hibernate:
      ddl-auto: update

    show-sql: true
